# Generated by Django 3.2.6 on 2021-08-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('no_hp', models.CharField(max_length=14, unique=True)),
                ('status_verif', models.CharField(choices=[('SUDAH', 'sudah'), ('BELUM', 'belum')], default='BELUM', max_length=5)),
                ('referral', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Kode referral tidak dikenali')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
