# Generated by Django 3.2.6 on 2021-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='no_hp',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
